version: '3.1'

services:

  postgres:
    container_name: reformcity-postgres
    env_file:
      - .env
    build:
      context: ./docker/postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - reformcity
    expose:
      - 5432
    ports:
      - '5432:5432'

  nginx:
    container_name: reformcity-nginx
    build:
      context: ./docker/nginx
      args:
        - USER_USERNAME
        - USER_UID
        - USER_GID
        - DOCKER_FRONTEND_HOST
        - DOCKER_BACKEND_HOST
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - '80:80'
      - '443:443'
    links:
      - php
    depends_on:
      - php
    networks:
      - reformcity

  php:
    container_name: reformcity-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./docker/php
      args:
        - USER_USERNAME
        - USER_UID
        - USER_GID
    environment:
      PHP_IDE_CONFIG: serverName=docker-cli
    secrets:
      - id_rsa
    volumes:
      - ./:/usr/share/nginx/html:rw
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - reformcity

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa

networks:
  reformcity:

volumes:
  postgres:
#    driver: local
